### ISSUE TITLE
Duplicate messages in history

### ISSUE THREAD

**Issue by RakkFourkites** [centrifugal/centrifuge#56] opened 2019-06-20 05:52 UTC
I have set history time limit to 1 hour in server.
When a client subscribes to channel, he gets the messages.
When he unsubscribes and again subscribes within 1 hour ,he will get some messages twice right.How to avoid reception of duplicate messages?

**Comment by FZambia** [comment] 2019-06-20 08:02
My first thoughts are that your expectations from history do not correlate with its implementation. History is a stream of messages in channel - if you ask history twice you will get the same messages.

If this answer is not helpful then please provide detailed reproducing example.

**Comment by RakkFourkites** [comment] 2019-06-24 05:29
Hey thanks!In server side, when I keep redis host as "localhost",it is working as expected, but when I replace redis host "localhost" by AWS Elastic Beanstalk endpoint, it's giving error on subscribing channel!
Why is it so?!

**Comment by FZambia** [comment] 2019-06-24 12:43
I can't answer without additional information - server logs, how endpoint looks like etc.

Closing this as your last question does not relate to original issue. Provide full context (server logs, versions, expected and actual behaviour, use case description and a way to reproduce) when opening issues or asking questions next time.

**Closed by FZambia** 2019-06-24 12:43 UTC
