### ISSUE TITLE
why do you use Redis Pubsub

### ISSUE THREAD

**Issue by HoangNgo88** [centrifugal/centrifuge#276] opened 2023-01-29 03:16 UTC
Hi, I am reading your project and I love this project
I have a question, why do you choose Redis Pubsub in your project instead of others like RabbitMQ or Kafka, are there any special features that others dont have it. Can you share me  it. I am wondering when I should choose Redis Pubsub instead of others like RabbitMQ or Kafka

**Comment by FZambia** [comment] 2023-01-29 14:25
Closing as duplicate of https://github.com/centrifugal/centrifugo/issues/606

**Closed by FZambia** 2023-01-29 14:25 UTC
